### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by ninja-yan** [blake-nouribekian/codeigniter-datatables#1]
Hello. I'm currently using ignited datatables to use datatables in codeigniter. I found this and want to try. I copied the getTable function from the data.php in my controller and changed the columns and database table. How can I add 'where' statement?

Another problem is I'm receiving an error message. Here's my jquery code
$('#users_table').dataTable({
            "sPaginationType": "full_numbers",
            "bProcessing": true,
            "bServerSide": true,
            "bJQueryUI": true,
            "bDeferRender": true,
            "sAjaxSource": "<?php echo base_url(); ?>/users/getTable",
            "sServerMethod": "POST",
            "aaSorting": [[6, "asc"]],
            "aoColumnDefs": [{
                'bSortable': false,
                'aTargets': [7]
            }]
        });

and this is the error
DataTables warning (table id = 'users_table'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.

**Comment by ninja-yan** [comment]
I want also to concatenate two columns

**Comment by dbryant** [comment]
I'm having an issue getting this to work.  I have know that the datatable call is being made but I am not getting any data back.  

I copied your getTable() function into my controller file and here is my datatable call.  Thank you in advance for any help that you can give.

$('#example_2').dataTable( {
    "sDom": "<'row'<'span5'><'span5'>r>Tt<'row'<'span5'i><'span7'p>>",

```
"oTableTools":{
        "sSwfPath": "assets/swf/copy_csv_xls_pdf.swf",
        "aButtons": ["csv","xls", "pdf"]
        },
"oColVis": {
    "buttonText": "Change columns"
},
"sPaginationType": "bootstrap",
"oLanguage": {
    "sLengthMenu": "_MENU_ records per page"
},
"bProcessing": true,
"bServerSide": true,
   "sAjaxSource": "data_tab/getTable",
   "aaSorting": [[9, "asc"]]
```

} );

**Comment by ghost** [comment]
ninja-yan, please look at my javascript configuration in the javascript.js file.

I am using "sServerMethod": "GET" and you are using "sServerMethod": "POST". The script MUST receive a GET request.

dbryant, I dont see "sServerMethod" in your code at all.  Please add  "sServerMethod": "GET" to the inital setup as well.

**Comment by blake-nouribekian** [comment]
ninja-yan,

Add the WHERE clause anywhere above the $this->db->select like this

$this->db->where('action !=', 'delete');
$this->db->select('SQL_CALC_FOUND_ROWS '.str_replace(' , ', ' ', implode(', ', $aColumns)), false);

If you want to concatenate 2 columns I would do it in SQL.
